[package]
name = "vulcan"
version = "0.1.3"
edition = "2021"

[lib]
name = "vulcan"
path = "src/lib.rs"

[dependencies]
reqwest = "0.11.24"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
