[package]
name = "vulcan"
version = "0.1.5"
edition = "2021"

[lib]
name = "vulcan"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
